apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: policy-todo.initialized
  argocd.argoproj.io/sync-wave: "-1"
spec:
  broker: todo-events
  filter:
    attributes:
      type: todo.initialized
  subscriber:
{{- if .Values.knative.eventing.local }}
    uri: {{ .Values.knative.eventing.subscriber }}/cloudevent/todo.initialized
{{- else }}
    ref:
{{- if .Values.knativeDeploy }}
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: {{ .Values.service.name }}
{{- else }}
      apiVersion: v1
      kind: Service
      name: {{ .Values.service.name }}
{{- end }}
    uri: /cloudevent/todo.initialized
{{- end }}